name: SCA with Snyk + SBOM for nodejs-goof

on:
  push:
    branches: [main]
  pull_request:

jobs:
  sca-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Snyk test (console output)
        uses: snyk/actions@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Install Snyk CLI and snyk-to-html
        run: |
          npm install -g snyk snyk-to-html

      - name: Generate Snyk HTML and JSON Reports
        run: |
          snyk test --json > snyk-report.json || true
          snyk-to-html -i snyk-report.json -o snyk-report.html || true

          echo "Report files:"
          ls -lh snyk-report.*

          if [ -s snyk-report.html ]; then
            echo "✅ HTML report generated"
          else
            echo "❌ HTML report was not generated correctly"
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Monitor project with Snyk
        run: snyk monitor || true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Upload Snyk reports
        uses: actions/upload-artifact@v4
        with:
          name: snyk-reports
          path: |
            snyk-report.json
            snyk-report.html

      # --- SBOM Generation and Scan using Docker ---

      - name: Generate SBOM using Syft (CycloneDX JSON)
        run: |
          docker run --rm -v ${{ github.workspace }}:/project anchore/syft:latest /project -o cyclonedx-json > sbom.json || true

      - name: Scan SBOM with Grype
        run: |
          docker run --rm -v ${{ github.workspace }}:/project anchore/grype sbom:/project/sbom.json -o table || true

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v4
        with:
          name: sbom-json
          path: sbom.json
