name: SCA with Snyk for nodejs-goof

on:
  push:
    branches: [main]
  pull_request:

jobs:
  snyk-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.3

      - name: Set up Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run Snyk to test for vulnerabilities (console output only)
        uses: snyk/actions@master
        with:
          command: test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Generate and save Snyk JSON report
        run: |
          snyk test --json > snyk-report.json || true

          if [ ! -s snyk-report.json ] || grep -q '"vulnerabilities":\s*\[\s*\]' snyk-report.json; then
            echo "No vulnerabilities found or file is empty."
          else
            echo "Snyk report generated with vulnerabilities:"
            cat snyk-report.json
          fi
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true

      - name: Upload Snyk report artifact
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json
